spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:postgresql://localhost:5433/finance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

service:
  app:
    secret:
      jwtCookieName: jwtToken
      jwtSecret: Jy1W8cDu5Yv5WDV1guCoJFgj7eJ7Gt9a1a26sdbjYjk
      jwtExpirationMs: 600000 # 10 min

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

logging:
  level:
    org.springframework.security.web: DEBUG