server:
  port: 8060

spring:
  config:
    import: "optional:configserver:http://localhost:8088"
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/users/auth/**
          - id: balance-service
            uri: lb://balance-service
            predicates:
              - Path=/balance/user/**
          - id: transaction-service
            uri: lb://transaction-service
            predicates:
              - Path=/transaction/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0